spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    properties:
      jadira:
        usertype:
          autoRegisterUserTypes: true
springfox:
  documentation:
    swagger:
      v2:
        path: /api

security:
  oauth2:
    returnUrl: http://training.opensource.io/admin/
    client:
      clientId: 12318639222-auop2ammp2i64ntb3qcaoq0srec7t8o7.apps.googleusercontent.com
      clientSecret: Jf7Mf_Nzz9FKdU4FwpI7JQEW
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope:
        - openid
        - email
        - profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true        
---
spring:
  profiles: localtest
  datasource:
    platform: h2
    schema: classpath:/scripts/sql/schema-h2.sql
    data: classpath:/scripts/sql/data-h2.sql
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        type: trace
security:
  oauth2:
    returnUrl: http://localhost:4201/admin/
server:
  address: localhost
  port: 8080
---
spring:
  profiles: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/storefrontdb
    username: storefront
    password: $70r3fr0n7
    platform: POSTGRESQL
    schemaName: TRAINING_STOREFRONT
security:
  oauth2:
    returnUrl: http://training.opensource.io/admin/